"use strict";

module.exports = {
    rules : {
        "at-rule-blacklist" : null,
        "at-rule-empty-line-before" : [ "always", {
            except : [ "first-nested" ],
            ignore : [ "blockless-after-blockless", "after-comment" ]
        }],
        "at-rule-name-case" : "lower",
        "at-rule-name-newline-after" : null,
        "at-rule-name-space-after" : "always",
        "at-rule-no-unknown" : [ true, {
            "ignoreAtRules" : [
                "value",
                "composes",
                "repeat",
            ]
        }],
        "at-rule-no-vendor-prefix" : true,
        "at-rule-semicolon-newline-after" : "always",
        "at-rule-semicolon-space-before" : "never",
        "at-rule-whitelist" : null,
        "block-closing-brace-empty-line-before" : "never",
        "block-closing-brace-newline-after" : "always",
        "block-closing-brace-newline-before" : "always",
        "block-closing-brace-space-after" : null,
        "block-closing-brace-space-before" : null,
        "block-no-empty" : true,
        "block-opening-brace-newline-after" : "always",
        "block-opening-brace-newline-before" : null,
        "block-opening-brace-space-after" : null,
        "block-opening-brace-space-before" : null,
        "color-hex-case" : "upper",
        "color-hex-length" : "short",
        "color-named" : "never",
        "color-no-hex" : null,
        "color-no-invalid-hex" : true,
        "comment-empty-line-before" : [ "always", {
            except : "first-nested",
            ignore : [ "after-comment", "stylelint-commands" ]
        }],
        "comment-no-empty" : true,
        "comment-whitespace-inside" : "always",
        "comment-word-blacklist" : null,
        "custom-media-pattern" : null,
        "custom-property-empty-line-before" : [ "always", {
            except : [ "after-comment", "after-custom-property", "first-nested" ]
        }],
        "custom-property-pattern" : null,
        "declaration-bang-space-after" : "never",
        "declaration-bang-space-before" : "always",
        "declaration-block-no-duplicate-properties" : [ true, {
            ignoreProperties : [ "composes" ]
        } ],
        "declaration-block-no-redundant-longhand-properties" : true,
        "declaration-block-no-shorthand-property-overrides" : true,
        "declaration-block-semicolon-newline-after" : "always",
        "declaration-block-semicolon-newline-before" : null,
        "declaration-block-semicolon-space-after" : null,
        "declaration-block-semicolon-space-before" : "never",
        "declaration-block-single-line-max-declarations" : 1,
        "declaration-block-trailing-semicolon" : "always",
        "declaration-colon-newline-after" : null,
        "declaration-colon-space-after" : "always-single-line",
        "declaration-colon-space-before" : "never",
        "declaration-empty-line-before" : [ "always", {
            except : [ "after-comment", "first-nested" ],
            ignore : [ "after-declaration" ]
        }],
        "declaration-no-important" : true,
        "declaration-property-unit-blacklist" : null,
        "declaration-property-unit-whitelist" : {
            // All animations should use ms for durations/delays
            "/^animation/" : [ "ms" ],
        },
        "declaration-property-value-blacklist" : null,
        "declaration-property-value-whitelist" : {
            // Font-size needs to always use a shared value
            "font-size" : [
                "/^sizes\\./",
                "/^calc\\(/",
                "/^fontscale\\(/",
            ],
        },
        "font-family-name-quotes" : "always-unless-keyword",
        "font-family-no-duplicate-names" : true,
        "font-weight-notation" : null,
        "function-blacklist" : null,
        "function-calc-no-unspaced-operator" : true,
        "function-comma-newline-after" : "always-multi-line",
        "function-comma-newline-before" : null,
        "function-comma-space-after" : "always-single-line",
        "function-comma-space-before" : "never",
        "function-linear-gradient-no-nonstandard-direction" : true,
        "function-max-empty-lines" : [ 1, { severity : "warning" } ],
        "function-name-case" : "lower",
        "function-parentheses-newline-inside" : "always-multi-line",
        "function-parentheses-space-inside" : "never-single-line",
        "function-url-no-scheme-relative" : true,
        "function-url-quotes" : "always",
        "function-url-scheme-blacklist" : null,
        "function-url-scheme-whitelist" : null,
        "function-whitelist" : null,
        "function-whitespace-after" : "always",
        "indentation" : 4,
        "keyframe-declaration-no-important" : true,
        "length-zero-no-unit" : true,
        "max-empty-lines" : [ 1, { severity : "warning" } ],
        "max-line-length" : null,
        "max-nesting-depth" : 2,
        "media-feature-colon-space-after" : "always",
        "media-feature-colon-space-before" : "never",
        "media-feature-name-blacklist" : null,
        "media-feature-name-case" : "lower",
        "media-feature-name-no-unknown" : true,
        "media-feature-name-no-vendor-prefix" : true,
        "media-feature-name-whitelist" : null,
        "media-feature-parentheses-space-inside" : "never",
        "media-feature-range-operator-space-after" : "always",
        "media-feature-range-operator-space-before" : "always",
        "media-query-list-comma-newline-after" : "never-multi-line",
        "media-query-list-comma-newline-before" : "never-multi-line",
        "media-query-list-comma-space-after" : "always",
        "media-query-list-comma-space-before" : "never",
        "no-descending-specificity" : true,
        "no-duplicate-selectors" : true,
        "no-empty-source" : true,
        "no-eol-whitespace" : [true, {
            ignore : [ "empty-lines" ]
        }],
        "no-extra-semicolons" : [ true, { severity : "warning" } ],
        "no-invalid-double-slash-comments" : true,
        "no-missing-end-of-source-newline" : true,
        "no-unknown-animations" : true,
        "number-leading-zero" : "always",
        "number-max-precision" : [ 3, { severity : "warning" } ],
        "number-no-trailing-zeros" : null,
        "property-blacklist" : [
            "box-sizing",
            "text-transform"
        ],
        "property-case" : "lower",
        "property-no-unknown" : [ true, {
            ignoreProperties : [ "composes" ]
        }],
        "property-no-vendor-prefix" : true,
        "property-whitelist" : null,
        "rule-empty-line-before" : [ "always-multi-line", {
            ignore : [ "after-comment" ],
            except : [ "first-nested" ]
        }],
        "selector-attribute-brackets-space-inside" : "never",
        "selector-attribute-operator-blacklist" : null,
        "selector-attribute-operator-space-after" : "never",
        "selector-attribute-operator-space-before" : "never",
        "selector-attribute-operator-whitelist" : null,
        "selector-attribute-quotes" : "always",
        "selector-class-pattern" : null,
        "selector-combinator-space-after" : "always",
        "selector-combinator-space-before" : "always",
        "selector-descendant-combinator-no-non-space" : true,
        "selector-id-pattern" : null,
        "selector-list-comma-newline-after" : "always",
        "selector-list-comma-newline-before" : null,
        "selector-list-comma-space-after" : null,
        "selector-list-comma-space-before" : "never",
        "selector-max-attribute" : null,
        "selector-max-class" : null,
        "selector-max-combinators" : null,
        "selector-max-compound-selectors" : null,
        "selector-max-empty-lines" : 0,
        "selector-max-id" : null,
        "selector-max-specificity" : null,
        "selector-max-type" : 0,
        "selector-max-universal" : null,
        "selector-nested-pattern" : null,
        "selector-no-qualifying-type" : true,
        "selector-no-vendor-prefix" : true,
        "selector-pseudo-class-blacklist" : null,
        "selector-pseudo-class-case" : "lower",
        "selector-pseudo-class-no-unknown" : [ true, {
            "ignorePseudoClasses" : [ "global", "external" ]
        }],
        "selector-pseudo-class-parentheses-space-inside" : "never",
        "selector-pseudo-class-whitelist" : null,
        "selector-pseudo-element-case" : "lower",
        "selector-pseudo-element-colon-notation" : "double",
        "selector-pseudo-element-no-unknown" : true,
        "selector-type-case" : "lower",
        "selector-type-no-unknown" : null,
        "shorthand-property-no-redundant-values" : true,
        "string-no-newline" : true,
        "string-quotes" : "double",
        "time-min-milliseconds" : null,
        "unit-blacklist" : null,
        "unit-case" : "lower",
        "unit-no-unknown" : true,
        "unit-whitelist" : null,
        "value-keyword-case" : null,
        "value-list-comma-newline-after" : "always-multi-line",
        "value-list-comma-newline-before" : null,
        "value-list-comma-space-after" : null,
        "value-list-comma-space-before" : "never",
        "value-list-max-empty-lines" : 0,
        "value-no-vendor-prefix" : true,
    }
};
