"use strict";

module.exports = {
    rules : {
        "order/order" : [
            "custom-properties",
            "declarations",
            "at-rules",
            "rules",
        ],

        "order/properties-order" : [
            // Property groups, inspired by https://pyx.space/post/keys-to-maintainable-css-order
            [
                {
                    groupName : "modular-css composition",
                    emptyLineBefore : "never",
                    properties : [
                        "composes",
                    ],
                },

                {
                    groupName : "stacking",
                    emptyLineBefore : "always",
                    properties : [
                        "z-index",
                    ],
                },

                {
                    groupName : "layout",
                    emptyLineBefore : "always",
                    properties : [
                        "grid-area",
                        "order",
                        "position",
                        "top",
                        "right",
                        "bottom",
                        "left",
                        "content",
                    ],
                },

                {
                    groupName : "box model",
                    emptyLineBefore : "always",
                    properties : [
                        "display",
                        "height",
                        "max-height",
                        "min-height",
                        "width",
                        "max-width",
                        "min-width",
                        "visibility",
                        "margin",
                        "margin-top",
                        "margin-right",
                        "margin-bottom",
                        "margin-left",
                        "padding",
                        "padding-top",
                        "padding-right",
                        "padding-bottom",
                        "padding-left",
                    ],
                },

                {
                    groupName : "border",
                    properties : [
                        "border",
                        "border-bottom",
                        "border-bottom-color",
                        "border-bottom-left-radius",
                        "border-bottom-right-radius",
                        "border-bottom-style",
                        "border-bottom-width",
                        "border-color",
                        "border-image",
                        "border-image-outset",
                        "border-image-repeat",
                        "border-image-slice",
                        "border-image-source",
                        "border-image-width",
                        "border-left",
                        "border-left-color",
                        "border-left-style",
                        "border-left-width",
                        "border-radius",
                        "border-right",
                        "border-right-color",
                        "border-right-style",
                        "border-right-width",
                        "border-style",
                        "border-top",
                        "border-top-color",
                        "border-top-left-radius",
                        "border-top-right-radius",
                        "border-top-style",
                        "border-top-width",
                        "border-width",
                    ],
                },

                {
                    groupName : "grid",
                    properties : [
                        // Grid parent
                        "grid",
                        "grid-auto-columns",
                        "grid-auto-flow",
                        "grid-auto-rows",
                        "grid-gap",
                        "gap",
                        "grid-column-gap",
                        "grid-row-gap",
                        "grid-template",
                        "grid-template-areas",
                        "grid-template-columns",
                        "grid-template-rows",

                        // Grid children
                        "grid-column",
                        "grid-column-start",
                        "grid-column-end",
                        "grid-row",
                        "grid-row-start",
                        "grid-row-end",
                        "justify-self",
                        "place-self",
                    ],
                },

                {
                    groupName : "flexbox",
                    properties : [
                        // Flex parent
                        "flex-direction",
                        "flex-wrap",
                        "flex-flow",
                        "justify-content",
                        "align-items",
                        "align-content",

                        // Flex children
                        "flex",
                        "flex-grow",
                        "flex-shrink",
                        "flex-basis",
                        "align-self",
                        "place-content",
                        "visibility",
                        "overflow",
                        "overflow-wrap",
                        "overflow-x",
                        "overflow-y",
                    ],
                },

                {
                    groupName : "visual",
                    emptyLineBefore : "always",
                    properties : [
                        "background",
                        "background-attachment",
                        "background-clip",
                        "background-color",
                        "background-image",
                        "background-origin",
                        "background-position",
                        "background-position-x",
                        "background-position-y",
                        "background-repeat",
                        "background-size",
                        "box-shadow",
                        "color",
                        "fill",
                        "mask",
                        "mask-border",
                        "mask-border-mode",
                        "mask-border-outset",
                        "mask-border-repeat",
                        "mask-border-slice",
                        "mask-border-source",
                        "mask-border-width",
                        "mask-clip",
                        "mask-composite",
                        "mask-image",
                        "mask-mode",
                        "mask-origin",
                        "mask-position",
                        "mask-repeat",
                        "mask-size",
                        "mask-type",
                        "opacity",
                        "stroke",
                        "stroke-dasharray",
                        "stroke-dashoffset",
                        "stroke-miterlimit",
                        "stroke-width",
                    ],
                },

                {
                    groupName : "type",
                    emptyLineBefore : "always",
                    properties : [
                        "font",
                        "font-family",
                        "font-feature-settings",
                        "font-kerning",
                        "font-language-override",
                        "font-optical-sizing",
                        "font-size",
                        "font-size-adjust",
                        "font-stretch",
                        "font-style",
                        "font-synthesis",
                        "font-variant",
                        "font-variant-alternates",
                        "font-variant-caps",
                        "font-variant-east-asian",
                        "font-variant-ligatures",
                        "font-variant-numeric",
                        "font-variant-position",
                        "font-variation-settings",
                        "font-weight",
                        "line-height",
                        "hanging-punctuation",
                        "hyphens",
                        "letter-spacing",
                        "line-break",
                        "overflow-wrap",
                        "paint-order",
                        "tab-size",
                        "text-align",
                        "text-align-last",
                        "text-indent",
                        "text-justify",
                        "text-size-adjust",
                        "text-transform",
                        "white-space",
                        "word-break",
                        "word-spacing",
                    ],
                },

                {
                    groupName : "transforms/transitions/animations",
                    emptyLineBefore : "always",
                    properties : [
                        "backface-visibility",
                        "clip-path",
                        "filter",
                        "perspective",
                        "perspective-origin",
                        "rotate",
                        "scale",
                        "transform",
                        "transform-box",
                        "transform-origin",
                        "transform-style",
                        "transition",
                        "transition-delay",
                        "transition-duration",
                        "transition-property",
                        "transition-timing-function",
                        "animation",
                        "animation-name",
                        "animation-delay",
                        "animation-direction",
                        "animation-duration",
                        "animation-fill-mode",
                        "animation-iteration-count",
                        "animation-play-state",
                        "animation-timing-function",
                    ],
                },

                {
                    groupName : "weird stuff",
                    emptyLineBefore : "always",
                    properties : [
                        "cursor",
                        "pointer-events",
                        "user-select",
                    ],
                },
            ],

            // Options
            { unspecified : "bottomAlphabetical" },
        ],
    }
};
